# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: ai-web

infra:
  provider: bicep
  path: infra

services:
  backend:
    host: containerapp
    image: ghcr.io/edgestream/ai-web-aguiserver:latest

  frontend:
    host: containerapp
    image: ghcr.io/edgestream/ai-web-aguichat:latest
