apiVersion: v1
kind: Service
metadata:
  name: ai-agents-frontend
  labels:
    app.kubernetes.io/name: ai-agents-frontend
spec:
  selector:
    app.kubernetes.io/name: ai-agents-frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
