apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-agents-frontend
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ai-agents-frontend
                port:
                  name: http
